language: python
sudo: required
dist: xenial
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
env:
  - FLASK=1.1.1
  - FLASK=1.0.4
  - FLASK=0.12.4
install:
  - pip install Flask==$FLASK
  - pip install -r dev_requirements.txt
script: python setup.py test
